global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql_metrics'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'mongo_metrics'
    static_configs:
      - targets: ['mongo_exporter:9216']